# kafka消费者配置

# kafka服务器地址
consumer.bootstrapservers: 118.25.46.85:9092

#  # 消费者群组ID，发布-订阅模式，即如果一个生产者生产的消息，多个消费者都要消费，那么需要定义自己的群组，同一个群组内的消费者只有一个能消费到消息
#  consumer.groupid: fireAlarm

# true，消费者的偏移量将在后台定期提交；false关闭自动提交位移，在消息被完整处理之后再手动提交位移
consumer.enableautocommit: true

# 如何设置为自动提交（enable.auto.commit=true）,这里设置自动提交周期
consumer.autocommitintervalms: 1000

# session.timeout.ms:在使用kafka的组管理时，用于检测消费者故障的超时
consumer.sessiontimeoutms: 30000

# 消费的topic偏移量
consumer.autooffsetreset: earliest

# key.serializer和value.serializer示例：将用户提供的key和value对象ProducerRecord转换成字节，你可以使用附带的ByteArraySerizlizaer或StringSerializer处理简单的byte和String类型
consumer.keydeserializer: org.apache.kafka.common.serialization.StringDeserializer
consumer.valuedeserializer: org.apache.kafka.common.serialization.StringDeserializer
